// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeSharingApi.DataLayer.Data;

#nullable disable

namespace RecipeSharingApi.DataLayer.Migrations
{
    [DbContext(typeof(RecipeSharingDbContext))]
    [Migration("20230531212400_RecipeSh10")]
    partial class RecipeSh10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollectionRecipe", b =>
                {
                    b.Property<Guid>("CollectionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CollectionsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("CollectionRecipe");
                });

            modelBuilder.Entity("PolicyRole", b =>
                {
                    b.Property<Guid>("PoliciesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PoliciesId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PolicyRole");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfRecipes")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.CookBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CookBook");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Cuisine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cuisines");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Mappings.PolicyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RoleId");

                    b.ToTable("PolicyRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf944e2d-44e9-49e2-ad70-d91bf375f0dc"),
                            PolicyId = new Guid("2bc75a12-6655-441c-af9d-32be58a5531e"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("d6c9da4b-9666-4885-b236-9701e29429c1"),
                            PolicyId = new Guid("6d966a93-0aa1-420b-bf37-d7288e8e638e"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("fb2752b6-dbdc-4103-9378-ac0cf2185a9d"),
                            PolicyId = new Guid("68d3008d-ede9-4ac8-8eb9-0f8877358476"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("b8a80d95-14c1-4f3d-95f0-e473f5c60cd4"),
                            PolicyId = new Guid("1381225f-387b-49c9-b57a-6a1a379fdb8a"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("7102bdb7-7642-466a-b3c2-d7a2b229e328"),
                            PolicyId = new Guid("410595d2-43e0-4844-b672-a59a4151d7d5"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("ff222385-81e3-4dfd-b3f4-6df2f77f8290"),
                            PolicyId = new Guid("e00b12ee-cde2-44e3-ba10-ef4b45390252"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("df443c46-1bd7-435b-b915-1e04f3f941c6"),
                            PolicyId = new Guid("403015ab-9012-42d8-b13b-65366085303a"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("9024f973-560a-478c-b188-1e73afe8424f"),
                            PolicyId = new Guid("1d77b3dd-fd7b-4db6-b528-a5c9470378dd"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("6a89a49a-8930-428b-a75e-674215d0b7d7"),
                            PolicyId = new Guid("ec67c7c7-653d-4078-b9ec-82f9d188fd69"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("e413b4ab-9cec-44b4-9a50-622292ecb581"),
                            PolicyId = new Guid("8884e0bf-6477-4efc-b5e2-a34fe1d1dda5"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("7fca53a4-757d-4b00-b423-7bf6cb6a85e4"),
                            PolicyId = new Guid("0fce3dfd-befa-47f7-8a66-07964b6d8f4d"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("0fb58aa4-d10e-428d-9d80-8eca07675764"),
                            PolicyId = new Guid("d2194a88-8cb5-41c3-b40d-227ea502c1a8"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("8254ad4e-9bda-46f8-96d9-89f591992f5f"),
                            PolicyId = new Guid("58b74ad0-74c8-4909-b79b-60d31a57e49b"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("53107267-7db6-4371-8a39-b8d500d5a03e"),
                            PolicyId = new Guid("d0f9bb82-9abe-4841-ab56-dd79cff023d3"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("375cda87-83be-4427-a255-ff810e1735bc"),
                            PolicyId = new Guid("cefaeb1f-7ca5-41dd-bd1c-e0b66f5f6051"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("8d44139c-81fc-4764-90e1-2eaab2e4dad0"),
                            PolicyId = new Guid("6929858c-31ad-40b0-b53d-bc0cc30548ab"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("bb43096e-6e43-4976-a74b-e0d3873ea577"),
                            PolicyId = new Guid("6f563976-863c-409d-8237-f08ed043ffcd"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("2c5af8fa-b4d7-4c46-a271-517024f4edef"),
                            PolicyId = new Guid("257400bf-1dbf-4f30-83d7-d1f482651a8d"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("6a70449d-7bd9-482c-9ed2-f20f66b4b460"),
                            PolicyId = new Guid("71c436da-3849-4459-8f26-7b299c74162f"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("8577e681-2c76-4fa0-aa2a-96afa49bf034"),
                            PolicyId = new Guid("1f1260ac-260e-4bc8-8cb3-a7fa5d8dc366"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("640353e0-5bcc-459f-8b66-7d36202fe7ff"),
                            PolicyId = new Guid("bf9f8380-023f-4660-9c0f-f8fce5295f48"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("d51a914f-905c-43e9-a6f0-d20e2e45d0de"),
                            PolicyId = new Guid("8460422a-5e83-4d24-82a2-eeb45b902406"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("b523d61e-c252-4a6d-aa9a-9861d76251d4"),
                            PolicyId = new Guid("d787eb55-0b45-45c6-a6fb-0566209831b0"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("8119d26a-ed79-4543-b997-e51529b34ee7"),
                            PolicyId = new Guid("ccb9a20c-6dc2-4c37-a792-33790c42e256"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("845fb6e1-024b-4e78-bc83-5c050268c2fc"),
                            PolicyId = new Guid("2844b8fb-a338-4801-b06b-6f80d923d6c2"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("e40c28ea-32fa-4c91-9c11-6118a2383081"),
                            PolicyId = new Guid("d6a80b7d-70f3-4a63-a1a4-7ff70c110a49"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("c52a71c3-3d2f-4b2d-aef2-869b7ca3352c"),
                            PolicyId = new Guid("e8fbc57b-4837-4d73-be89-e9f6ce4dc328"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("a011e3a5-06b9-4fba-a4b9-9a9bc74a0138"),
                            PolicyId = new Guid("d5662e2c-f6db-4601-8911-a3faf99d03d2"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("d4863607-64c1-4ddb-8836-fd125c5535a2"),
                            PolicyId = new Guid("ea13f8d7-a3ed-4464-bfbb-f4af8db2b567"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("1ee64810-7333-43ae-a318-c6f9374cabc5"),
                            PolicyId = new Guid("c3001055-9124-4aea-a1ac-2dccb4257512"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("c3c23837-1e6d-44ec-bab6-744e081b6411"),
                            PolicyId = new Guid("a80c3363-4977-49f5-9327-1c9b76baa3ed"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("bf3fba91-bc29-40a9-a7a0-949f2d71b01b"),
                            PolicyId = new Guid("0d423b1a-3bc6-48f3-bc9c-c1bb8d5a7071"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("08386fa8-8491-44b2-a6d3-8b25ebf365f5"),
                            PolicyId = new Guid("3eb0b264-294e-4a1d-a748-5610d2a1f1f1"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("fea28b08-c019-472b-91e7-fb273a955875"),
                            PolicyId = new Guid("5d5a00cb-4c9c-4950-aace-8dd956eaec0c"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("82207918-f621-4b24-998c-faeb3edbc768"),
                            PolicyId = new Guid("1b68dcb1-d256-4d9e-93f7-51008c268cb9"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("87a547d2-6c24-4327-a31a-f87fec52678e"),
                            PolicyId = new Guid("0fce3dfd-befa-47f7-8a66-07964b6d8f4d"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("eae81830-f78d-441d-9fd5-9f28eef10b58"),
                            PolicyId = new Guid("d2194a88-8cb5-41c3-b40d-227ea502c1a8"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("bbde4f98-c619-4cfe-9ec7-231ed0164ae7"),
                            PolicyId = new Guid("43d2a293-4093-42fd-b80e-c146f5890076"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("9f14248c-d1eb-4b59-b460-c4f81e15400f"),
                            PolicyId = new Guid("384a15ef-8a8f-4152-8c3c-196749f9ab72"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("2fffa6b8-3cae-430d-ac77-c18aed59dff0"),
                            PolicyId = new Guid("9b0a1cbc-bb03-48c7-89dd-24b622e6cb84"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("f50ac3c4-5261-4850-a393-ab0f2f3f113d"),
                            PolicyId = new Guid("2c497d51-de9d-41a7-b23b-c4f51f6dd9d6"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("2c9171d6-ba11-47ad-b2ce-c37ac04e9703"),
                            PolicyId = new Guid("3d041ace-b9ef-425f-b520-136e2dc8c5ba"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("063282fd-1a93-49f8-b956-1527799ec029"),
                            PolicyId = new Guid("a9401ffb-8d6a-47cd-b9ba-d5d740bb86f8"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("a499bd30-8515-4130-be15-0cbc1463da94"),
                            PolicyId = new Guid("0c19f0c5-3da9-435f-b784-81482e074738"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("bb014183-164a-4360-8e43-47c19c43a6f7"),
                            PolicyId = new Guid("e8fbc57b-4837-4d73-be89-e9f6ce4dc328"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("293f0f89-dd04-4fbb-b4b8-90a717211b9d"),
                            PolicyId = new Guid("d5662e2c-f6db-4601-8911-a3faf99d03d2"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("8cd2bb4d-35f9-4670-abc9-b3c7177177c3"),
                            PolicyId = new Guid("ea13f8d7-a3ed-4464-bfbb-f4af8db2b567"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("befc38cf-b2f4-4212-b5fe-38b28df1647f"),
                            PolicyId = new Guid("c3001055-9124-4aea-a1ac-2dccb4257512"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("16c5fda3-d490-47c0-bb26-7a0281ed0d88"),
                            PolicyId = new Guid("a80c3363-4977-49f5-9327-1c9b76baa3ed"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("de661027-a9f1-4e7d-8409-82bd9924bcb4"),
                            PolicyId = new Guid("0d423b1a-3bc6-48f3-bc9c-c1bb8d5a7071"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("42569bf5-37d2-466b-bb2c-2347fceae1fe"),
                            PolicyId = new Guid("3eb0b264-294e-4a1d-a748-5610d2a1f1f1"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("e5be2eea-b888-4a30-acc1-ad890b8ffd75"),
                            PolicyId = new Guid("5d5a00cb-4c9c-4950-aace-8dd956eaec0c"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("010d9c89-fc25-4a03-adfb-15c7b433410d"),
                            PolicyId = new Guid("1b68dcb1-d256-4d9e-93f7-51008c268cb9"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("fabc897b-11c2-40bc-9800-a9148b2a05a4"),
                            PolicyId = new Guid("0fce3dfd-befa-47f7-8a66-07964b6d8f4d"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("19c0cdd3-3964-4ded-a0c9-acf811938908"),
                            PolicyId = new Guid("d2194a88-8cb5-41c3-b40d-227ea502c1a8"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("aaac76f6-db4a-4b8b-b7f0-f1cf00073509"),
                            PolicyId = new Guid("43d2a293-4093-42fd-b80e-c146f5890076"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("4bdb6db9-9476-4b7e-9d06-66df061404c1"),
                            PolicyId = new Guid("384a15ef-8a8f-4152-8c3c-196749f9ab72"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("74204d5d-05ff-4052-b581-1634ceaab895"),
                            PolicyId = new Guid("9b0a1cbc-bb03-48c7-89dd-24b622e6cb84"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("102f3a03-8753-427b-8623-4cdb4f090a2f"),
                            PolicyId = new Guid("2c497d51-de9d-41a7-b23b-c4f51f6dd9d6"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("10fbd1d8-88df-48af-b956-fb6c66071d3a"),
                            PolicyId = new Guid("3d041ace-b9ef-425f-b520-136e2dc8c5ba"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("7a07fde4-0d6c-4dd4-87d9-b099fa3d446c"),
                            PolicyId = new Guid("e73cf4bb-4a96-49c2-a3ef-428915e2f968"),
                            RoleId = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd")
                        },
                        new
                        {
                            Id = new Guid("04e578ae-8046-41d4-afaa-bc2a9da1600e"),
                            PolicyId = new Guid("0e8e465e-8abd-4c2f-a6a3-3796b0d702bc"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("601b8e73-de27-48b2-b226-1c7a03615c63"),
                            PolicyId = new Guid("d0f9bb82-9abe-4841-ab56-dd79cff023d3"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("01457afe-d826-4bd5-88b3-6e9d63b7678c"),
                            PolicyId = new Guid("ad057d33-b1ab-491f-a143-a7cd45399a7b"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("a78ce896-1244-449d-9f09-11a226c6a76d"),
                            PolicyId = new Guid("ae6e7487-2375-4e33-911c-74ca4d375f5a"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("4ec0f02c-8236-48ae-b98a-8a7ed17a23e5"),
                            PolicyId = new Guid("3b90b27c-5690-4305-a418-3f58efeade35"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("7fef7347-f240-46e2-be28-336223b030af"),
                            PolicyId = new Guid("f7d9d48f-62c4-44eb-9ac8-1e7ce066c88d"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("c58b4ff4-a015-4014-9977-98521b269259"),
                            PolicyId = new Guid("97fa4a01-82c8-4ea2-addc-cc5f4037dc1e"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("28533d8b-365b-455b-b0bb-654852f40a55"),
                            PolicyId = new Guid("2b0088ca-6ee6-41a7-b931-ee61f786bd55"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("6e604266-f58b-4da7-ac1e-fa4558349a2d"),
                            PolicyId = new Guid("71c436da-3849-4459-8f26-7b299c74162f"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("f11b64b8-5d86-47b2-a00f-a21243d3fe1c"),
                            PolicyId = new Guid("bf9f8380-023f-4660-9c0f-f8fce5295f48"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("e8cb52da-99ac-4761-bc0e-2f46bd457278"),
                            PolicyId = new Guid("cefaeb1f-7ca5-41dd-bd1c-e0b66f5f6051"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("cd3d7298-ea3f-486e-bc7d-67449549f971"),
                            PolicyId = new Guid("6929858c-31ad-40b0-b53d-bc0cc30548ab"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("5d64bfd8-d37a-4532-afa8-c48c86e7849b"),
                            PolicyId = new Guid("6f563976-863c-409d-8237-f08ed043ffcd"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("ee625111-da9e-40fa-98cf-24639488621f"),
                            PolicyId = new Guid("257400bf-1dbf-4f30-83d7-d1f482651a8d"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("3ae26d69-270f-4d91-93a7-9818f905ce9f"),
                            PolicyId = new Guid("71c436da-3849-4459-8f26-7b299c74162f"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("c330f51e-88b5-4624-bf98-0ea1ba7ec77e"),
                            PolicyId = new Guid("1f1260ac-260e-4bc8-8cb3-a7fa5d8dc366"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("44112be0-f6ee-41e7-b8ee-be15bbd78d32"),
                            PolicyId = new Guid("8460422a-5e83-4d24-82a2-eeb45b902406"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("06e921d3-df39-4aa0-a241-e8c1785a5fe5"),
                            PolicyId = new Guid("d787eb55-0b45-45c6-a6fb-0566209831b0"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("5d29dfec-ae72-4d3b-aafb-3cc529741ce3"),
                            PolicyId = new Guid("ccb9a20c-6dc2-4c37-a792-33790c42e256"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("eb9cf856-31ab-47af-a4e3-eb1fde0d34aa"),
                            PolicyId = new Guid("2844b8fb-a338-4801-b06b-6f80d923d6c2"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("c2c4746d-ed7e-4843-9fbb-eb1dda2b755e"),
                            PolicyId = new Guid("d6a80b7d-70f3-4a63-a1a4-7ff70c110a49"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("58e6dc43-4cd2-4034-96d3-a083edc3bd0a"),
                            PolicyId = new Guid("e73cf4bb-4a96-49c2-a3ef-428915e2f968"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("8f437899-beff-4a1a-87f3-8cd507ea76a8"),
                            PolicyId = new Guid("a9401ffb-8d6a-47cd-b9ba-d5d740bb86f8"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("96e505f7-3f75-458b-a6db-5b93b6ecd05a"),
                            PolicyId = new Guid("0c19f0c5-3da9-435f-b784-81482e074738"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("ff636c4f-9f1d-44ce-8b8e-ac253b8f8a85"),
                            PolicyId = new Guid("e8fbc57b-4837-4d73-be89-e9f6ce4dc328"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("74cc82d3-f5d1-4224-88fa-4d75e83db327"),
                            PolicyId = new Guid("d5662e2c-f6db-4601-8911-a3faf99d03d2"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("9bae4fad-8125-47b4-a3a6-e10199ac1d23"),
                            PolicyId = new Guid("ea13f8d7-a3ed-4464-bfbb-f4af8db2b567"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("b43e07fd-f23a-4063-90f6-4ced65e7a879"),
                            PolicyId = new Guid("c3001055-9124-4aea-a1ac-2dccb4257512"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("e00e2252-367e-473c-b4a7-f7b3a91a6def"),
                            PolicyId = new Guid("8f69170f-064c-40b2-804e-c4b53bb3218d"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("69a0df84-f8b5-4638-b0bc-aea14572c1a4"),
                            PolicyId = new Guid("65ab361d-916d-43cd-816f-49ed8688bf87"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("c8b8ce4c-f183-4ddd-9861-797d7348835c"),
                            PolicyId = new Guid("a80c3363-4977-49f5-9327-1c9b76baa3ed"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("e45be0ff-5ce3-4989-a3c6-12d5c46f9f59"),
                            PolicyId = new Guid("0d423b1a-3bc6-48f3-bc9c-c1bb8d5a7071"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("69156c00-237a-4519-ae4d-c961e14990f8"),
                            PolicyId = new Guid("3eb0b264-294e-4a1d-a748-5610d2a1f1f1"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("1dee0a57-1fde-4b9d-ae4e-8467eb6fcd50"),
                            PolicyId = new Guid("5d5a00cb-4c9c-4950-aace-8dd956eaec0c"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("f02106e3-57ac-4029-83c0-1a9b8eedb13d"),
                            PolicyId = new Guid("43d2a293-4093-42fd-b80e-c146f5890076"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("95d1229e-7b2a-48a0-84e5-7e1cd2c7b729"),
                            PolicyId = new Guid("3d041ace-b9ef-425f-b520-136e2dc8c5ba"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        },
                        new
                        {
                            Id = new Guid("1da61afd-fdab-485c-8b72-ba21b9dc3f1c"),
                            PolicyId = new Guid("9b0a1cbc-bb03-48c7-89dd-24b622e6cb84"),
                            RoleId = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d")
                        });
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Mappings.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Mappings.RecipeInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StepDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("InstructionSteps");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2bc75a12-6655-441c-af9d-32be58a5531e"),
                            Name = "GetNameOfUser"
                        },
                        new
                        {
                            Id = new Guid("6d966a93-0aa1-420b-bf37-d7288e8e638e"),
                            Name = "addrole"
                        },
                        new
                        {
                            Id = new Guid("68d3008d-ede9-4ac8-8eb9-0f8877358476"),
                            Name = "addPolicy"
                        },
                        new
                        {
                            Id = new Guid("1381225f-387b-49c9-b57a-6a1a379fdb8a"),
                            Name = "addRolePolicy"
                        },
                        new
                        {
                            Id = new Guid("410595d2-43e0-4844-b672-a59a4151d7d5"),
                            Name = "getRoles"
                        },
                        new
                        {
                            Id = new Guid("e00b12ee-cde2-44e3-ba10-ef4b45390252"),
                            Name = "getPolicies"
                        },
                        new
                        {
                            Id = new Guid("0e8e465e-8abd-4c2f-a6a3-3796b0d702bc"),
                            Name = "PostCollections"
                        },
                        new
                        {
                            Id = new Guid("d0f9bb82-9abe-4841-ab56-dd79cff023d3"),
                            Name = "getCollections"
                        },
                        new
                        {
                            Id = new Guid("ad057d33-b1ab-491f-a143-a7cd45399a7b"),
                            Name = "getCollectionsById"
                        },
                        new
                        {
                            Id = new Guid("ae6e7487-2375-4e33-911c-74ca4d375f5a"),
                            Name = "putCollections"
                        },
                        new
                        {
                            Id = new Guid("3b90b27c-5690-4305-a418-3f58efeade35"),
                            Name = "getUserCollections"
                        },
                        new
                        {
                            Id = new Guid("f7d9d48f-62c4-44eb-9ac8-1e7ce066c88d"),
                            Name = "deleteCollections"
                        },
                        new
                        {
                            Id = new Guid("97fa4a01-82c8-4ea2-addc-cc5f4037dc1e"),
                            Name = "postRecipeInCollections"
                        },
                        new
                        {
                            Id = new Guid("2b0088ca-6ee6-41a7-b931-ee61f786bd55"),
                            Name = "RemoveRecipeCollections"
                        },
                        new
                        {
                            Id = new Guid("cefaeb1f-7ca5-41dd-bd1c-e0b66f5f6051"),
                            Name = "PostCookbooks"
                        },
                        new
                        {
                            Id = new Guid("6929858c-31ad-40b0-b53d-bc0cc30548ab"),
                            Name = "AllCookbooks"
                        },
                        new
                        {
                            Id = new Guid("6f563976-863c-409d-8237-f08ed043ffcd"),
                            Name = "AllUserCookbooks"
                        },
                        new
                        {
                            Id = new Guid("257400bf-1dbf-4f30-83d7-d1f482651a8d"),
                            Name = "GetCookbookById"
                        },
                        new
                        {
                            Id = new Guid("71c436da-3849-4459-8f26-7b299c74162f"),
                            Name = "AllCookbooksByPage"
                        },
                        new
                        {
                            Id = new Guid("1f1260ac-260e-4bc8-8cb3-a7fa5d8dc366"),
                            Name = "UpdateCookBook"
                        },
                        new
                        {
                            Id = new Guid("bf9f8380-023f-4660-9c0f-f8fce5295f48"),
                            Name = "DeleteCookbook"
                        },
                        new
                        {
                            Id = new Guid("8460422a-5e83-4d24-82a2-eeb45b902406"),
                            Name = "AddRecipeOnCookbook"
                        },
                        new
                        {
                            Id = new Guid("d787eb55-0b45-45c6-a6fb-0566209831b0"),
                            Name = "DeleteRecipeFromCookbook"
                        },
                        new
                        {
                            Id = new Guid("403015ab-9012-42d8-b13b-65366085303a"),
                            Name = "CreateCuisine"
                        },
                        new
                        {
                            Id = new Guid("1d77b3dd-fd7b-4db6-b528-a5c9470378dd"),
                            Name = "UpdateCuisine"
                        },
                        new
                        {
                            Id = new Guid("ec67c7c7-653d-4078-b9ec-82f9d188fd69"),
                            Name = "DeleteCuisine"
                        },
                        new
                        {
                            Id = new Guid("ccb9a20c-6dc2-4c37-a792-33790c42e256"),
                            Name = "CreateRecipe"
                        },
                        new
                        {
                            Id = new Guid("2844b8fb-a338-4801-b06b-6f80d923d6c2"),
                            Name = "UpdateRecipe"
                        },
                        new
                        {
                            Id = new Guid("8884e0bf-6477-4efc-b5e2-a34fe1d1dda5"),
                            Name = "GetRecipeByUserId"
                        },
                        new
                        {
                            Id = new Guid("d6a80b7d-70f3-4a63-a1a4-7ff70c110a49"),
                            Name = "GetAllUserRecipe"
                        },
                        new
                        {
                            Id = new Guid("e73cf4bb-4a96-49c2-a3ef-428915e2f968"),
                            Name = "DeleteRecipe"
                        },
                        new
                        {
                            Id = new Guid("a9401ffb-8d6a-47cd-b9ba-d5d740bb86f8"),
                            Name = "ReviewRecipe"
                        },
                        new
                        {
                            Id = new Guid("0c19f0c5-3da9-435f-b784-81482e074738"),
                            Name = "UpdateReviews"
                        },
                        new
                        {
                            Id = new Guid("e8fbc57b-4837-4d73-be89-e9f6ce4dc328"),
                            Name = "DelteRewiews"
                        },
                        new
                        {
                            Id = new Guid("d5662e2c-f6db-4601-8911-a3faf99d03d2"),
                            Name = "CreateShopingList"
                        },
                        new
                        {
                            Id = new Guid("ea13f8d7-a3ed-4464-bfbb-f4af8db2b567"),
                            Name = "DeleteItemFromShopingList"
                        },
                        new
                        {
                            Id = new Guid("c3001055-9124-4aea-a1ac-2dccb4257512"),
                            Name = "GetItemFromShopingListById"
                        },
                        new
                        {
                            Id = new Guid("8f69170f-064c-40b2-804e-c4b53bb3218d"),
                            Name = "GetLink"
                        },
                        new
                        {
                            Id = new Guid("65ab361d-916d-43cd-816f-49ed8688bf87"),
                            Name = "GetUserShopingList"
                        },
                        new
                        {
                            Id = new Guid("a80c3363-4977-49f5-9327-1c9b76baa3ed"),
                            Name = "GetAllTags"
                        },
                        new
                        {
                            Id = new Guid("0d423b1a-3bc6-48f3-bc9c-c1bb8d5a7071"),
                            Name = "GetATagById"
                        },
                        new
                        {
                            Id = new Guid("3eb0b264-294e-4a1d-a748-5610d2a1f1f1"),
                            Name = "CreateATag"
                        },
                        new
                        {
                            Id = new Guid("5d5a00cb-4c9c-4950-aace-8dd956eaec0c"),
                            Name = "UpdateTag"
                        },
                        new
                        {
                            Id = new Guid("1b68dcb1-d256-4d9e-93f7-51008c268cb9"),
                            Name = "DeleteTag"
                        },
                        new
                        {
                            Id = new Guid("0fce3dfd-befa-47f7-8a66-07964b6d8f4d"),
                            Name = "DeleteUser"
                        },
                        new
                        {
                            Id = new Guid("d2194a88-8cb5-41c3-b40d-227ea502c1a8"),
                            Name = "AllUsers"
                        },
                        new
                        {
                            Id = new Guid("58b74ad0-74c8-4909-b79b-60d31a57e49b"),
                            Name = "searchByEmail"
                        },
                        new
                        {
                            Id = new Guid("43d2a293-4093-42fd-b80e-c146f5890076"),
                            Name = "ChangePassword"
                        },
                        new
                        {
                            Id = new Guid("384a15ef-8a8f-4152-8c3c-196749f9ab72"),
                            Name = "GetUserById"
                        },
                        new
                        {
                            Id = new Guid("9b0a1cbc-bb03-48c7-89dd-24b622e6cb84"),
                            Name = "UpdateUser"
                        },
                        new
                        {
                            Id = new Guid("2c497d51-de9d-41a7-b23b-c4f51f6dd9d6"),
                            Name = "UpdateUserRole"
                        },
                        new
                        {
                            Id = new Guid("3d041ace-b9ef-425f-b520-136e2dc8c5ba"),
                            Name = "MyData"
                        });
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudioInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<Guid?>("CookBookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<Guid>("CuisineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yield")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CookBookId");

                    b.HasIndex("CuisineId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.RecommendationScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RecommendationScore");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ad84fe7-65f5-44a5-bf99-7727744dfedd"),
                            Name = "admin"
                        },
                        new
                        {
                            Id = new Guid("24bade73-46d0-40dd-95e7-42352504fe2d"),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("ed263967-56fd-451c-a997-952d26cf7aff"),
                            Name = "editor"
                        });
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id", "UserId", "Name");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingListItem");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaltedHashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecipesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("RecipeTag");
                });

            modelBuilder.Entity("CollectionRecipe", b =>
                {
                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolicyRole", b =>
                {
                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Policy", null)
                        .WithMany()
                        .HasForeignKey("PoliciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Collection", b =>
                {
                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.CookBook", b =>
                {
                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Mappings.PolicyRole", b =>
                {
                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Policy", "Policies")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policies");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Mappings.RecipeIngredient", b =>
                {
                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Mappings.RecipeInstruction", b =>
                {
                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Recipe", b =>
                {
                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.CookBook", "CookBook")
                        .WithMany("Recipes")
                        .HasForeignKey("CookBookId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Cuisine", "Cuisine")
                        .WithMany("Recipes")
                        .HasForeignKey("CuisineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CookBook");

                    b.Navigation("Cuisine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Review", b =>
                {
                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Recipe", "Recipe")
                        .WithMany("Reviews")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.ShoppingListItem", b =>
                {
                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.User", b =>
                {
                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeSharingApi.DataLayer.Models.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.CookBook", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Cuisine", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RecipeSharingApi.DataLayer.Models.Entities.User", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
